class Ref: ...
class CgProfile: ...

class ObjectData:
    def __add__(
        self, other: bytes | bytearray | Ref | Sym | ObjectData
    ) -> ObjectData: ...

class Sym: ...
class FxconvError(Exception): ...

def ref(
    base: bytes | bytearray | str | ObjectData,
    offset: int | None = None,
    padding: int | None = None,
    prefix_underscore: bool = True,
    align: int | None = None,
) -> Ref: ...
def u8(value: int, check: bool = False) -> bytes: ...
def u16(value: int, check: bool = False) -> bytes: ...
def u32(value: int, check: bool = False) -> bytes: ...
def i8(value: int, check: bool = False) -> bytes: ...
def i16(value: int, check: bool = False) -> bytes: ...
def i32(value: int, check: bool = False) -> bytes: ...
def ptr(
    base: bytes | bytearray | str | ObjectData,
    offset: int | None = None,
    padding: int | None = None,
    prefix_underscore: bool = True,
    align: int | None = None,
) -> Ref: ...
def chars(
    text: str,
    length: int,
    require_final_nul: bool = True,
) -> bytes: ...
def string(text: str) -> Ref: ...
def sym(name: str) -> Sym: ...
def elf(
    data: bytes | bytearray | ObjectData,
    output: str,
    symbol: str,
    toolchain: str | None = None,
    arch: str | None = None,
    section: str | None = None,
    assembly: str | None = None,
    outputtarget: str | None = None,
) -> None: ...
